tap 'universal-ctags/universal-ctags'
tap 'johanhaleby/kubetail'
tap 'heroku/brew'

brew 'ansible'
brew 'zsh'
brew 'gist'
brew 'git'
brew 'go'
brew 'goenv'
brew 'htop'
brew 'irssi'
brew 'jq'
brew 'kubectl'
brew 'kubetail'
brew 'npm'
brew 'mongodb'
brew 'postgresql'
brew 'python3'
brew 'rabbitmq'
brew 'rbenv'
brew 'redis'
brew 'ripgrep'
brew 'ruby-build'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'wget'
brew 'watch'





